<?php
if(isset($_GET['page'])){
 	$test='view/'.$_GET["page"].".php";
 	if(file_exists($test)){
 		$page="view/".$_GET['page'];
 		$title=$_GET['page'];
 	}
 	else{
 		$page="view/accueil";
 	}
 }
 elseif(isset($_GET['controlleur'])){
 	$page="controlleur/".$_GET["controlleur"];
 	$title=$_GET['controlleur'];
 }
 else{
 	$page="view/accueil";
 }
include_once("view/header.php");
include_once("view/menu.php");
include_once($page.'.php');
include_once("view/footer.php");
?>